#!/usr/bin/env python3
"""Thumbnails of the bestiary artwork for bestiary.html.

  python3 tools/bestiar-obrazky.py ../hof/src/main/webapp/WEB-INF/img/beast public/beast src/data/beastImages.js

Reads <key>.jpg from hof WEB-INF/img/beast (artwork of every monster except the humanoids composed
from layers), writes public/beast/<key>.jpg (260 px wide, only new or changed files) and the list
of keys to src/data/beastImages.js.
"""
import json
import os
import sys

from PIL import Image

src, out, js = sys.argv[1:4]
W = 260
os.makedirs(out, exist_ok=True)
keys = []
for name in sorted(os.listdir(src)):
    if not name.lower().endswith('.jpg'):
        continue
    key = name[:-4]
    sp, dst = os.path.join(src, name), os.path.join(out, key + '.jpg')
    if not os.path.exists(dst) or os.path.getmtime(dst) < os.path.getmtime(sp):
        im = Image.open(sp).convert('RGB')
        im.resize((W, round(im.height * W / im.width)), Image.LANCZOS).save(dst, quality=78, optimize=True, progressive=True)
    keys.append(key)
with open(js, 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by tools/bestiar-obrazky.py: bestiary keys with artwork in public/beast/<key>.jpg (hof WEB-INF/img/beast).\n')
    f.write('export const BEAST_IMAGES = new Set(' + json.dumps(keys) + ');\n')
print(len(keys), 'images ->', out)
