import * as THREE from 'three';
import { BESTIARY, BESTIARY_GROUPS } from '../data/bestiary.js';
import { BEAST_IMAGES } from '../data/beastImages.js';
import { creatureFor, beastBody } from '../avatar/creatures.js';
import { bodyFor } from '../avatar/bodies.js';
import { ProceduralAvatar } from '../renderer/ProceduralAvatar.js';
import { ProceduralHorse } from '../renderer/ProceduralHorse.js';
import { createCreature, CREATURE_RIGS } from '../renderer/creatureRigs.js';

/*
 * Bestiary preview (bestiary.html): every monster of the hof bestiary (src/data/bestiary.js, generated by
 * tools/bestiar-modely.py) with the 3D model the client shows for it.
 *   done – a creature rig of its own (avatar/creatures.js), the horse, or a humanoid whose body fits (group 'humanoid')
 *   part – humanoid body exists but a part is missing (group 'humanoid+': wings, head, tail …)
 *   miss – no model yet: the arena shows a stand-in; the card says which rig is proposed
 * Thumbnails are rendered once by one offscreen renderer; the selected monster is animated in the live viewer.
 * Artwork of the monster (hof WEB-INF/img/beast, thumbnails in public/beast by tools/bestiar-obrazky.py) is the picture
 * of a missing model and the reference next to a finished one.
 */

const STATES = [['idle', 'klid'], ['walk', 'chůze'], ['run', 'běh'], ['attack', 'útok'], ['defend', 'obrana'], ['hit', 'zásah'],
    ['kneel', 'klek / sed'], ['lie', 'leh'], ['death', 'smrt']];
const DURATION = { attack: .7, defend: .8, hit: .45 };
const HORSES = ['horse', 'war-horse'];
const STATUS_TEXT = { done: 'hotovo', part: 'doplněk', miss: 'chybí' };
const GROUP = Object.fromEntries(BESTIARY_GROUPS.map(g => [g.id, g]));
const artOf = b => BEAST_IMAGES.has(b.key) ? `./beast/${b.key}.jpg` : null;
const NO_ART = "this.closest('.pic,.card,.info,.empty')?.classList.add('noart');this.remove()";

// ------------------------------------------------------------------ status + model of a beast
function lookOf(b) {
    const layers = [];
    if (b.hair && b.hair.startsWith('hair') && b.hair !== 'hair-horns') layers.push(b.hair);
    if (b.beard && b.beard.startsWith('beard')) layers.push(b.beard);
    return { base: beastBody(b.key) || b.lookBase || 'male', variant: b.lookVariant || '', layers };
}
function statusOf(b) {
    if (creatureFor(b.key) || HORSES.includes(b.key)) return 'done';
    const body = bodyFor(beastBody(b.key) || b.lookBase, b.lookVariant);
    const humanoidBody = !body.creature && body.humanoid && !String(b.lookBase).startsWith('horse');
    if (b.group === 'humanoid' && humanoidBody) return 'done';
    if (b.group === 'humanoid+' && humanoidBody) return 'part';
    return 'miss';
}
function modelText(b) {
    const cr = creatureFor(b.key);
    if (cr) return `${CREATURE_RIGS[cr.rig].title} – varianta <code>${cr.variant}</code>`;
    if (HORSES.includes(b.key)) return 'ProceduralHorse';
    if (b.status === 'miss') return `zatím zástupce (2D sprite <code>${b.lookBase || '–'}</code> nemá 3D kostru)`;
    return `postava (ProceduralAvatar), tělo <code>${beastBody(b.key) || b.lookBase}${b.lookVariant ? ' / ' + b.lookVariant : ''}</code>`;
}
function buildModel(b) {
    const cr = creatureFor(b.key);
    if (cr) return createCreature(cr);
    if (HORSES.includes(b.key)) return new ProceduralHorse();
    return new ProceduralAvatar(lookOf(b));
}

const beasts = BESTIARY.map(b => ({ ...b, status: null }));
for (const b of beasts) b.status = statusOf(b);

// ------------------------------------------------------------------ shared scene setup
function makeScene(bg) {
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(bg);
    scene.add(new THREE.HemisphereLight(0xe8f0ff, 0x5c4c3b, 2));
    const sun = new THREE.DirectionalLight(0xfff1d2, 2.8);
    sun.position.set(-4, 9, 6);
    sun.castShadow = true;
    sun.shadow.mapSize.set(1024, 1024);
    Object.assign(sun.shadow.camera, { left: -5, right: 5, top: 5, bottom: -5, far: 30 });
    scene.add(sun);
    const ground = new THREE.Mesh(new THREE.CircleGeometry(6, 40), new THREE.MeshStandardMaterial({ color: 0x55743f, roughness: 1 }));
    ground.rotation.x = -Math.PI / 2;
    ground.receiveShadow = true;
    scene.add(ground);
    return scene;
}
const actor = (state = 'idle') => ({ state, direction: 'E', speed: 3, runMultiplier: 1.5, actionTime: 0, actionDuration: 0,
    get facing() { return this.direction; } });
const _box = new THREE.Box3(), _mb = new THREE.Box3(), _size = new THREE.Vector3(), _ctr = new THREE.Vector3();
// Bounding box of the visible body only (hidden effect meshes – attack arc, guard sphere, halos – would shrink the model).
function bodyBox(root) {
    root.updateMatrixWorld(true);
    _box.makeEmpty();
    root.traverse(o => {
        if (!o.isMesh || !o.geometry) return;
        for (let p = o; p; p = p.parent) if (!p.visible) return;
        const m = o.material;
        if (m && (m.blending === THREE.AdditiveBlending || (m.transparent && m.opacity < .05))) return;
        if (!o.geometry.boundingBox) o.geometry.computeBoundingBox();
        _box.union(_mb.copy(o.geometry.boundingBox).applyMatrix4(o.matrixWorld));
    });
    return _box;
}
function frame(camera, root, angle = .75, k = 1) {
    bodyBox(root);
    _box.getSize(_size); _box.getCenter(_ctr);
    const r = Math.max(_size.y, _size.x * .8, _size.z * .8, .6);
    const dist = r * 2.4 * k;
    camera.position.set(_ctr.x + Math.sin(angle) * dist, _ctr.y + r * .55, _ctr.z + Math.cos(angle) * dist);
    camera.lookAt(_ctr.x, _ctr.y * .95, _ctr.z);
    return { center: _ctr.clone(), r };
}

// ------------------------------------------------------------------ cards
const groupsEl = document.getElementById('groups');
const cards = new Map();
for (const g of BESTIARY_GROUPS) {
    const list = beasts.filter(b => b.group === g.id);
    if (!list.length) continue;
    const order = { done: 0, part: 1, miss: 2 };
    list.sort((a, b) => order[a.status] - order[b.status] || (a.cz || a.key).localeCompare(b.cz || b.key, 'cs'));
    const n = s => list.filter(b => b.status === s).length;
    const sec = document.createElement('section');
    sec.className = 'group';
    sec.dataset.group = g.id;
    sec.innerHTML = `<h3>${g.title} <small>${list.length} · ${n('done') ? `<span class="badge done">${n('done')} hotovo</span>` : ''}
        ${n('part') ? `<span class="badge part">${n('part')} doplněk</span>` : ''} ${n('miss') ? `<span class="badge miss">${n('miss')} chybí</span>` : ''}</small></h3>
        <p class="how">${g.how}</p><div class="grid"></div>`;
    const grid = sec.querySelector('.grid');
    for (const b of list) {
        const el = document.createElement('div');
        el.className = 'card ' + b.status;
        el.tabIndex = 0;
        const name = b.cz || b.en || b.key, art = artOf(b);
        el.innerHTML = b.status === 'miss'
            ? `<div class="pic${art ? ' art' : ''}">${art ? `<img alt="" loading="lazy" src="${art}" onerror="${NO_ART}">` : ''}
                 <span class="q">?</span><span class="lt">chybí 3D model</span><span class="lb">2D: ${b.lookBase || '–'}</span></div>
               <span class="badge miss">chybí</span>
               <div class="txt"><div class="nm">${name}</div><div class="key">${b.key}</div>${b.note ? `<div class="note">${b.note}</div>` : ''}</div>`
            : `<div class="pic"><span class="wait">vykresluji…</span></div><span class="badge ${b.status}">${STATUS_TEXT[b.status]}</span>
               ${art ? `<img class="mini" alt="" loading="lazy" src="${art}" title="předloha (img/beast)" onerror="this.remove()">` : ''}
               <div class="txt"><div class="nm">${name}</div><div class="key">${b.key}</div>${b.status === 'part' ? `<div class="note">chybí: ${b.note}</div>` : ''}</div>`;
        el.addEventListener('click', () => select(b, true));
        el.addEventListener('keydown', e => { if (e.key === 'Enter') select(b, true); });
        grid.appendChild(el);
        cards.set(b.key, el);
    }
    groupsEl.appendChild(sec);
}

// summary + filters
const count = s => beasts.filter(b => !s || b.status === s).length;
document.getElementById('n-all').textContent = count();
for (const s of ['done', 'part', 'miss']) document.getElementById('n-' + s).textContent = count(s);
document.getElementById('progress').innerHTML = [['done', 'var(--accent)'], ['part', 'var(--warn)'], ['miss', 'var(--miss)']]
    .map(([s, c]) => `<i style="width:${count(s) / beasts.length * 100}%;background:${c}" title="${STATUS_TEXT[s]}: ${count(s)}"></i>`).join('');
let filter = 'all', query = '';
function applyFilter() {
    const q = query.trim().toLowerCase();
    for (const b of beasts) {
        const hit = (filter === 'all' || b.status === filter) && (!q || [b.cz, b.en, b.key].some(t => (t || '').toLowerCase().includes(q)));
        cards.get(b.key).classList.toggle('hidden', !hit);
    }
    for (const sec of groupsEl.children) sec.classList.toggle('hidden', !sec.querySelector('.card:not(.hidden)'));
}
document.getElementById('bar').addEventListener('click', e => {
    const chip = e.target.closest('.chip');
    if (!chip) return;
    filter = chip.dataset.f;
    document.querySelectorAll('.chip').forEach(c => c.classList.toggle('on', c === chip));
    applyFilter();
});
document.getElementById('q').addEventListener('input', e => { query = e.target.value; applyFilter(); });

// ------------------------------------------------------------------ thumbnails (one offscreen renderer)
const thumbs = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true });
thumbs.setSize(320, 240);
thumbs.shadowMap.enabled = true;
const tScene = makeScene(0x10140f);
const tCam = new THREE.PerspectiveCamera(30, 4 / 3, .05, 100);
const queue = beasts.filter(b => b.status !== 'miss');
function renderThumb(b) {
    const m = buildModel(b);
    tScene.add(m.root);
    const c = actor();
    for (let i = 0; i < 40; i++) m.update(c, 1 / 60);
    frame(tCam, m.root, .75, .86);
    thumbs.render(tScene, tCam);
    const url = thumbs.domElement.toDataURL('image/jpeg', .85);
    tScene.remove(m.root);
    const pic = cards.get(b.key)?.querySelector('.pic');
    if (pic) pic.innerHTML = `<img alt="" src="${url}">`;
}
function pump() {
    const t0 = performance.now();
    while (queue.length && performance.now() - t0 < 30) renderThumb(queue.shift());
    if (queue.length) setTimeout(pump, 0);
}

// ------------------------------------------------------------------ live viewer
const canvas = document.getElementById('live');
const stage = document.getElementById('stage');
const live = new THREE.WebGLRenderer({ antialias: true, canvas });
live.setPixelRatio(Math.min(devicePixelRatio, 2));
live.shadowMap.enabled = true;
live.shadowMap.type = THREE.PCFSoftShadowMap;
const lScene = makeScene(0x0f130e);
const lCam = new THREE.PerspectiveCamera(30, 1, .05, 100);
let cur = null, view = { angle: .75, zoom: 1.15, center: new THREE.Vector3(0, .8, 0), r: 1 };

const animsEl = document.getElementById('anims');
for (const [s, label] of STATES) {
    const btn = document.createElement('button');
    btn.textContent = label;
    btn.dataset.s = s;
    btn.onclick = () => setState(s);
    animsEl.appendChild(btn);
}
const turn = document.createElement('button');
turn.textContent = 'otočit 45°';
const DIRS = ['S', 'SW', 'W', 'NW', 'N', 'NE', 'E', 'SE'];
turn.onclick = () => { if (cur) cur.c.direction = DIRS[(DIRS.indexOf(cur.c.direction) + 1) % 8]; };
animsEl.appendChild(turn);

function setState(s) {
    if (!cur) return;
    cur.c.state = s;
    cur.c.actionDuration = cur.c.actionTime = DURATION[s] || 0;
    animsEl.querySelectorAll('button[data-s]').forEach(b => b.classList.toggle('on', b.dataset.s === s));
}

function select(b, scroll) {
    document.querySelectorAll('.card.sel').forEach(c => c.classList.remove('sel'));
    cards.get(b.key)?.classList.add('sel');
    if (cur) { lScene.remove(cur.m.root); cur = null; }
    stage.classList.toggle('missing', b.status === 'miss');
    const g = GROUP[b.group];
    const art = artOf(b);
    document.getElementById('empty').innerHTML = `${art ? `<img alt="" src="${art}" onerror="this.remove()">` : ''}
        <div class="msg"><div style="font-size:34px;font-weight:700;line-height:1">?</div>
        <b>${b.cz || b.key}</b> zatím nemá 3D model.<br>Navržená kostra: ${g ? g.title : '–'}${b.note ? ' – ' + b.note : ''}.<br>
        <span style="color:#c99a8f">V aréně se teď ukáže zástupná postava.</span></div>`;
    if (b.status !== 'miss') {
        const m = buildModel(b);
        lScene.add(m.root);
        const c = actor();
        for (let i = 0; i < 30; i++) m.update(c, 1 / 60);
        cur = { b, m, c };
        const f = frame(lCam, m.root, view.angle, view.zoom);
        view.center = f.center; view.r = f.r;
        setState('idle');
    }
    document.getElementById('info').innerHTML = `
        ${art ? `<img class="art" alt="${b.cz || b.key}" src="${art}" title="předloha: hof img/beast/${b.key}.jpg" onerror="this.remove()">` : ''}
        <span class="badge ${b.status}">${STATUS_TEXT[b.status]}</span>
        <h2>${b.cz || b.en || b.key}</h2><div class="en">${b.en || ''}</div>
        <dl>
          <dt>klíč</dt><dd><code>beast-${b.key}</code></dd>
          <dt>3D model</dt><dd>${modelText(b)}</dd>
          ${b.status !== 'done' ? `<dt>chybí</dt><dd>${b.status === 'part' ? b.note : 'celý 3D model' + (b.note ? ' – ' + b.note : '')}</dd>` : ''}
          <dt>skupina</dt><dd>${g ? g.title : b.group}</dd>
          <dt>2D sprite</dt><dd><code>${b.lookBase || '–'}${b.lookVariant ? ' / ' + b.lookVariant : ''}</code></dd>
          ${b.size !== null && b.size !== undefined ? `<dt>velikost</dt><dd>${b.size}</dd>` : ''}
        </dl>
        ${b.desc ? `<p class="desc">${b.desc}</p>` : ''}
        ${b.status === 'done' && !creatureFor(b.key) && !HORSES.includes(b.key) ? '<p class="desc" style="color:var(--muted);font-size:12px">Bez výbavy – v aréně ji server skládá z předmětů nestvůry.</p>' : ''}`;
    if (scroll) stage.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

let drag = null;
canvas.addEventListener('pointerdown', e => { drag = e.clientX; canvas.setPointerCapture(e.pointerId); });
canvas.addEventListener('pointermove', e => { if (drag !== null) { view.angle -= (e.clientX - drag) * .01; drag = e.clientX; } });
canvas.addEventListener('pointerup', () => { drag = null; });
canvas.addEventListener('wheel', e => { e.preventDefault(); view.zoom = THREE.MathUtils.clamp(view.zoom * (e.deltaY > 0 ? 1.1 : .9), .45, 3); }, { passive: false });

function resize() {
    const w = stage.clientWidth, h = stage.clientHeight;
    live.setSize(w, h, false);
    lCam.aspect = w / Math.max(1, h);
    lCam.updateProjectionMatrix();
}
new ResizeObserver(resize).observe(stage);
resize();

const clock = new THREE.Clock();
function loop() {
    const dt = Math.min(clock.getDelta(), .05);
    if (cur) {
        const c = cur.c;
        if (DURATION[c.state]) { c.actionTime -= dt; if (c.actionTime <= 0) c.actionTime += c.actionDuration; }
        cur.m.update(c, dt);
        const dist = view.r * 2.4 * view.zoom, k = view.center;
        lCam.position.set(k.x + Math.sin(view.angle) * dist, k.y + view.r * .55, k.z + Math.cos(view.angle) * dist);
        lCam.lookAt(k.x, k.y * .9, k.z);
    }
    live.render(lScene, lCam);
    requestAnimationFrame(loop);
}

const first = new URLSearchParams(location.search).get('beast');
select(beasts.find(b => b.key === first) || beasts.find(b => b.key === 'wolf') || beasts[0], false);
applyFilter();
loop();
pump();
